### ISSUE TITLE
关于依赖和运行设备的一些问题

### ISSUE THREAD

**Issue by wahaha-1** [superheroYu/RL_UAV_CPPandDHMulti#1]
1，依赖：需要降低numpy版本，我使用1.20能运行起来；需要安装cv2：pip install opencv-python；需要安装：pip install protobuf==3.19.0；需要安装：pip install tensorboard
2，请问您运行起来GPU调用正常吗？我的设备是i7-11800H+3060 6G，运行的时候GPU占用只有不到10%,但CPU占用有90%Y以上
3，请问能介绍一下tensorboard如何使用？是和一般用法一样吗？

**Comment by tp320621** [comment]
> 1，依赖：需要降低numpy版本，我使用1.20能运行起来;需要安装cv2：pip install opencv-python;需要安装：pip install protobuf==3.19.0;需要安装：pip install tensorboard 2，请问您运行起来GPU调用正常吗？我的设备是i7-11800H+3060 6G，运行的时候GPU占用只有不到10%，但CPU占用有90%Y以上 3，请问能介绍一下tensorboard如何使用？是和一般用法一样吗？

请问一下，显示ValueError: 需要指定参数文件！报错怎么解决呀？

**Comment by superheroYu** [comment]
> 1，依赖：需要降低numpy版本，我使用1.20能运行起来；需要安装cv2：pip install opencv-python；需要安装：pip install protobuf==3.19.0；需要安装：pip install tensorboard 2，请问您运行起来GPU调用正常吗？我的设备是i7-11800H+3060 6G，运行的时候GPU占用只有不到10%,但CPU占用有90%Y以上 3，请问能介绍一下tensorboard如何使用？是和一般用法一样吗？

更新了环境依赖，RL中的CPU消耗高是正常的，且环境部分的代码与原作者实现的思路一致，没有经过太多优化，想提高gpu使用率可以尝试增加神经网络训练中的bath size. tensorboard可以在vscode或者cursor中根据编辑器的提示打开也可以在终端输入tensorboard --logdir logs，用浏览器打开输出的网址。

**Comment by superheroYu** [comment]
> > 1，依赖：需要降低numpy版本，我使用1.20能运行起来;需要安装cv2：pip install opencv-python;需要安装：pip install protobuf==3.19.0;需要安装：pip install tensorboard 2，请问您运行起来GPU调用正常吗？我的设备是i7-11800H+3060 6G，运行的时候GPU占用只有不到10%，但CPU占用有90%Y以上 3，请问能介绍一下tensorboard如何使用？是和一般用法一样吗？
> 
> 请问一下，显示ValueError: 需要指定参数文件！报错怎么解决呀？

请按照readme中的训练方法指定参数文件。

**Comment by sunqinqiang** [comment]
请问一下在本代码当中运行python train.py --target CPP --config config/manhattan32_cpp.json --id manhattan32_cpp的时候会报错是怎么回事，readme上面写的是可以把DH替换成cpp的啊？

**Comment by superheroYu** [comment]
> 请问一下在本代码当中运行python train.py --target CPP --config config/manhattan32_cpp.json --id manhattan32_cpp的时候会报错是怎么回事，readme上面写的是可以把DH替换成cpp的啊？

是scikit-image库的版本问题，一个函数的参数过时了，上次适配新版没有测试到，现在已经修复了，可以再次clone或下载zip

**Comment by sunqinqiang** [comment]
感谢作者的回复，这波辛苦作者了，但是我这边还有一些问题想向您请教一下

**Comment by sunqinqiang** [comment]
(torch) E:\RL_UAV_CPPandDHMulti-main>python eval.py --target CPP --weights models/manhattan32_cpp_best --config config/manhattan32_cpp.json --id manhattan32_eval --samples 100                
正在解析配置文件 config/manhattan32_cpp.json 并将其传递到主函数
logs/manhattan32_eval
Traceback (most recent call last):
  File "E:\RL_UAV_CPPandDHMulti-main\eval.py", line 65, in <module>
    mc_cpp(args, params)
  File "E:\RL_UAV_CPPandDHMulti-main\eval.py", line 34, in mc_cpp
    env.agent.load_weights(args.weights) # 加载模型权重
  File "E:\RL_UAV_CPPandDHMulti-main\src\DDQN\Agent.py", line 206, in load_weights
    self.q_network.load_state_dict(torch.load(path))
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/manhattan32_cpp_best'

(torch) E:\RL_UAV_CPPandDHMulti-main>
想问一下作者在终端输入有关manhanttan32_cpp.json和urban50_cpp.json评估指令的时候会报错是怎么回事啊？

**Comment by sunqinqiang** [comment]
请问一下就是在本代码当中运行python train.py --target DHMulti --config config/urban50_DHMulti.json --id urban50_DHMulti 的时候会报错是怎么回事，还是说本代码目前只支持32地图版本的？

**Comment by sunqinqiang** [comment]
(torch1) E:\RL_UAV_CPPandDHMulti-main 1>python train.py --target DHMulti --config config/urban50_DHMulti.json --id urban50_DHMulti                 
正在解析配置文件 config/urban50_DHMulti.json 并将其传递到主函数
logs/urban50_DHMulti 已经存在.
是否覆盖日志文件? [Y/n]
y
删除旧日志
logs/urban50_DHMulti
正在填充经验回放池
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25000.0/25000.0 [00:18<00:00, 1326.28it/s]
正在执行： urban50_DHMulti
  1%|██                                                                                                                                                                                                                            | 37737/4000000 [27:20<40:39:23, 27.07it/s]Traceback (most recent call last):
  File "E:\RL_UAV_CPPandDHMulti-main 1\train.py", line 60, in <module>
    main_dhmulti(params)
  File "E:\RL_UAV_CPPandDHMulti-main 1\train.py", line 24, in main_dhmulti
    env.run()
  File "E:\RL_UAV_CPPandDHMulti-main 1\src\Base\Environment.py", line 83, in run
    self.stats.save_if_best()  # 如果当前代理模型是最好的，则保存它
  File "E:\RL_UAV_CPPandDHMulti-main 1\src\ModelStats.py", line 106, in save_if_best
    if self.params.save_model_path != '':
AttributeError: 'types.SimpleNamespace' object has no attribute 'save_model_path'
  1%|██                                                                                                                                                                                                                            | 37737/4000000 [27:29<48:06:05, 22.88it/s]

(torch1) E:\RL_UAV_CPPandDHMulti-main 1>

**Comment by superheroYu** [comment]
> (torch1) E:\RL_UAV_CPPandDHMulti-main 1>python train.py --target DHMulti --config config/urban50_DHMulti.json --id urban50_DHMulti 正在解析配置文件 config/urban50_DHMulti.json 并将其传递到主函数 logs/urban50_DHMulti 已经存在. 是否覆盖日志文件? [Y/n] y 删除旧日志 logs/urban50_DHMulti 正在填充经验回放池 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25000.0/25000.0 [00:18<00:00, 1326.28it/s] 正在执行： urban50_DHMulti 1%|██ | 37737/4000000 [27:20<40:39:23, 27.07it/s]Traceback (most recent call last): File "E:\RL_UAV_CPPandDHMulti-main 1\train.py", line 60, in main_dhmulti(params) File "E:\RL_UAV_CPPandDHMulti-main 1\train.py", line 24, in main_dhmulti env.run() File "E:\RL_UAV_CPPandDHMulti-main 1\src\Base\Environment.py", line 83, in run self.stats.save_if_best() # 如果当前代理模型是最好的，则保存它 File "E:\RL_UAV_CPPandDHMulti-main 1\src\ModelStats.py", line 106, in save_if_best if self.params.save_model_path != '': AttributeError: 'types.SimpleNamespace' object has no attribute 'save_model_path' 1%|██ | 37737/4000000 [27:29<48:06:05, 22.88it/s]
> 
> (torch1) E:\RL_UAV_CPPandDHMulti-main 1>

一个报错路径的bug，已经修复，可以重新clone

**Comment by superheroYu** [comment]
> (torch) E:\RL_UAV_CPPandDHMulti-main>python eval.py --target CPP --weights models/manhattan32_cpp_best --config config/manhattan32_cpp.json --id manhattan32_eval --samples 100 正在解析配置文件 config/manhattan32_cpp.json 并将其传递到主函数 logs/manhattan32_eval Traceback (most recent call last): File "E:\RL_UAV_CPPandDHMulti-main\eval.py", line 65, in mc_cpp(args, params) File "E:\RL_UAV_CPPandDHMulti-main\eval.py", line 34, in mc_cpp env.agent.load_weights(args.weights) # 加载模型权重 File "E:\RL_UAV_CPPandDHMulti-main\src\DDQN\Agent.py", line 206, in load_weights self.q_network.load_state_dict(torch.load(path)) File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 1479, in load with _open_file_like(f, "rb") as opened_file: File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 759, in _open_file_like return _open_file(name_or_buffer, mode) File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 740, in **init** super().**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: 'models/manhattan32_cpp_best'
> 
> (torch) E:\RL_UAV_CPPandDHMulti-main> 想问一下作者在终端输入有关manhanttan32_cpp.json和urban50_cpp.json评估指令的时候会报错是怎么回事啊？

需要先训练得到模型

**Comment by sunqinqiang** [comment]
还有就是我训练四种情况也是按照python train.py --target DHMulti --config config/manhattan32_DHMulti.json --id manhattan32_DHMulti 这条指令把manhattan32_DHMulti换成另外三种运行就可以吗？

**Comment by superheroYu** [comment]
> 还有就是我训练四种情况也是按照python train.py --target DHMulti --config config/manhattan32_DHMulti.json --id manhattan32_DHMulti 这条指令把manhattan32_DHMulti换成另外三种运行就可以吗？

--target只能选择CPP或DHMuliti,--config是配置参数文件的地址，--id随意填，是为了区别试验。更换地图请在配置文件中改，将配置文件中的关于地图的路径修改成其他的

**Comment by sunqinqiang** [comment]
好的，还有就是评估指令我输入非manhattan32_DHMulti 的指令就像下面这种
(torch) E:\RL_UAV_CPPandDHMulti-main>python eval.py --target CPP --weights models/manhattan32_cpp_best --config config/manhattan32_cpp.json --id manhattan32_eval --samples 100             
正在解析配置文件 config/manhattan32_cpp.json 并将其传递到主函数
logs/manhattan32_eval
Traceback (most recent call last):
  File "E:\RL_UAV_CPPandDHMulti-main\eval.py", line 65, in <module>
    mc_cpp(args, params)
  File "E:\RL_UAV_CPPandDHMulti-main\eval.py", line 34, in mc_cpp
    env.agent.load_weights(args.weights) # 加载模型权重
  File "E:\RL_UAV_CPPandDHMulti-main\src\DDQN\Agent.py", line 206, in load_weights
    self.q_network.load_state_dict(torch.load(path))
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/manhattan32_cpp_best'

(torch) E:\RL_UAV_CPPandDHMulti-main>
是怎么回事，是我直接换地图名称的方式不对还是说代码需要在更新一下？

**Comment by sunqinqiang** [comment]
好的，还有就是评估指令我输入非manhattan32_DHMulti 的指令就像下面这种
(torch) E:\RL_UAV_CPPandDHMulti-main>python eval.py --target CPP --weights models/manhattan32_cpp_best --config config/manhattan32_cpp.json --id manhattan32_eval --samples 100
正在解析配置文件 config/manhattan32_cpp.json 并将其传递到主函数
logs/manhattan32_eval
Traceback (most recent call last):
File "E:\RL_UAV_CPPandDHMulti-main\eval.py", line 65, in
mc_cpp(args, params)
File "E:\RL_UAV_CPPandDHMulti-main\eval.py", line 34, in mc_cpp
env.agent.load_weights(args.weights) # 加载模型权重
File "E:\RL_UAV_CPPandDHMulti-main\src\DDQN\Agent.py", line 206, in load_weights
self.q_network.load_state_dict(torch.load(path))
File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 1479, in load
with _open_file_like(f, "rb") as opened_file:
File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 759, in _open_file_like
return _open_file(name_or_buffer, mode)
File "D:\anaconda3\envs\torch\lib\site-packages\torch\serialization.py", line 740, in init
super().init(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/manhattan32_cpp_best'

(torch) E:\RL_UAV_CPPandDHMulti-main>
怎样先训练得到模型，是先运行一遍python train.py --target CPP --config config/manhattan32_cpp.json --id manhattan32_cpp得到结果以后在运行python train.py --target CPP --config config/manhattan32_cpp.json --id manhattan32_cpp的时候运行 python eval.py --target CPP --weights models/manhattan32_cpp_best --config config/manhattan32_cpp.json --id manhattan32_eval --samples 100指令吗？

**Comment by kryptoniancode** [comment]
@superheroYu It runs very slow, I have ran it for 11 hours, then it reach 17%, after that my system restarts, and again I have to run, is there way to speed it up?
